variables:
    GIT_DEPTH: 10


stages:
    - test_home

# just tests stow - what else can I do?
install_home_packages:
    stage: test_home

    image: ubuntu:20.04

    before_script:
        # update apt-get
        - apt-get update
        - apt-get -y install stow

    script:
        - stow home
