stages:
    - install_packages

install_packages:
    stage: install

    image: ubuntu:19.10

    before_install:
        sudo apt-get -y install $(cat packages.txt)

    addons:
        apt:
            update: true

    script:
        source install_scripts/install_vim.sh
        source install_scripts/install_tmux.sh
        source install_scripts/install_fonts.sh
        source install_scripts/install_zsh.sh
