variables:
    GIT_DEPTH: 10


stages:
    - install_packages_personal
    - test_config_install

# these tests check that "common" installations work
install_vim:
    stage: install_packages_personal

    image: ubuntu:19.10

    before_script:
        # update apt-get
        - apt-get update
        - apt-get -y install vim git
        - ln -fsn vim/vimrc ~/.vimrc

    script:
        - source install_scripts/install_vim.sh

install_tmux:
    stage: install_packages_personal

    image: ubuntu:19.10

    before_script:
        - apt-get update
        - apt-get -y install tmux git
        - ln -fsn tmux/tmux.common.conf ~/.tmux.common.conf
        - ln -fsn tmux/tmux.conf ~/.tmux.conf

    script:
        - source install_scripts/install_tmux.sh
        - source install_scripts/install_fonts.sh

install_zsh:
    stage: install_packages_personal

    image: ubuntu:19.10

    before_script:
        # update apt-get
        - apt-get update
        - apt-get -y install zsh curl git

    script:
        - echo "Installing oh-my-zsh ....."
        - sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
        - echo "Installing zsh packages..."
        #- git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k
        - git clone https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
        - git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        - git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        - echo "Done"

# check that all config files can be correctly installed
install_config_sam:
    stage: test_config_install
    
    script:
        - source install_scripts/install_sam.sh

install_config_lxplus:
    stage: test_config_install
    
    script:
        - source install_scripts/install_lxplus.sh

install_config_mac:
    stage: test_config_install
    
    script:
        - source install_scripts/install_mac.sh

install_config_manchester:
    stage: test_config_install
    
    script:
        - source install_scripts/install_manchester.sh
