stages:
    - install_packages_personal

install_packages_personal:
    stage: install_packages_personal

    image: ubuntu:19.10

    before_script:
        # update apt-get
        - apt-get update
        # only get packages that I need for testing
        - apt-get -y install vim tmux zsh git curl
        # Only link required dotfiles for now,
        # see issue #2...
        #- source install_scripts/install_sam.sh
        - ln -fsn vim/vimrc ~/.vimrc
        - ln -fsn zsh/zshrc_sam ~/.zshrc
        - ln -fsn zsh/zsh_aliases_personal ~/.zsh_aliases_personal
        - ln -fsn zsh/zsh_aliases_common ~/.zsh_aliases_common

    script:
        - source install_scripts/install_vim.sh
        - source install_scripts/install_tmux.sh
        - source install_scripts/install_fonts.sh
        - source install_scripts/install_zsh.sh
        - source install_scripts/install_zsh.sh
