stages:
    - install_packages

install_packages:
    stage: install_packages

    image: ubuntu:19.10

    before_script:
        - apt-get update
        # only get packages that I need for testing
        - apt-get -y install vim tmux zsh

    script:
        - source install_scripts/install_vim.sh
        - source install_scripts/install_tmux.sh
        - source install_scripts/install_fonts.sh
        - source install_scripts/install_zsh.sh
