stages:
    - install_packages_personal

install_packages_personal:
    stage: install_packages_personal

    image: ubuntu:19.10

    before_script:
        # update apt-get
        - apt-get update
        # only get packages that I need for testing
        - apt-get -y install vim tmux zsh git curl
        # link personal config files
        - source install_scripts/install_sam.sh

    script:
        - source install_scripts/install_vim.sh
        - source install_scripts/install_tmux.sh
        - source install_scripts/install_fonts.sh
        - source install_scripts/install_zsh.sh
