stages:
    - install_packages

install_packages:
    stage: install_packages

    image: ubuntu:19.10

    before_script:
        source install_scripts/install_apt_packages.sh

    script:
        source install_scripts/install_vim.sh
        source install_scripts/install_tmux.sh
        source install_scripts/install_fonts.sh
        source install_scripts/install_zsh.sh
