variables:
    GIT_DEPTH: 10


stages:
    - install

install_home:
    stage: install

    image: ubuntu:20.04

    before_script:
        # update apt-get
        - apt-get update
        - apt-get --assume-yes install stow vim git

    script:
        - source install_scripts/install_packages.sh
        - stow --no-folding home

#======================================================================================

install_lxplus:
    stage: install

    # ??
    image: ubuntu:20.04

    script:
        - source install_scripts/install_lxplus.sh
