stages:
    - install_packages_personal

install_vim:
    stage: install_packages_personal

    image: ubuntu:19.10

    before_script:
        # update apt-get
        - apt-get update
        - apt-get -y install vim git
        - ln -fsn vim/vimrc ~/.vimrc

    script:
        - source install_scripts/install_vim.sh

install_tmux:
    stage: install_packages_personal

    image: ubuntu:19.10

    before_script:
        - apt-get update
        - apt-get -y install tmux
        - ln -fsn tmux/tmux.common.conf ~/.tmux.common.conf
        - ln -fsn tmux/tmux.conf ~/.tmux.conf

    script:
        - source install_scripts/install_vim.sh
        - source install_scripts/install_tmux.sh
        - source install_scripts/install_fonts.sh
        - source install_scripts/install_zsh.sh

install_zsh:
    stage: install_packages_personal

    image: ubuntu:19.10

    before_script:
        # update apt-get
        - apt-get update
        - apt-get -y install zsh curl
        - ln -fsn zsh/zshrc_sam ~/.zshrc
        - ln -fsn zsh/zsh_aliases_common ~/.zsh_aliases_common

    script:
        - echo "Installing oh-my-zsh ....."
        - sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
        - echo "Installing zsh packages..."
        - git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k
        - git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        - git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        - echo "Done"
