#!/bin/bash

info=$(cmus-remote -Q 2> /dev/null)

if [ "$?" -ne 0 ]; then
	exit 0
fi

case $BLOCK_BUTTON in
	# left click = previous
	1) cmus-remote -r;;
	# middle click = pause
	2) cmus-remote -u;;
	# right click = next
	3) cmus-remote -n;;
esac
