#!/bin/sh

# i3blocks mail module.
# Displays number of unread mail and an loading icon if updating.
# When clicked, brings up `neomutt`.

case $BLOCK_BUTTON in
	1) "$TERMINAL" -e neomutt ;;
	2) setsid mailsync >/dev/null & ;;
esac

unread="$(find ~/.local/share/mail/*/INBOX/new/* -type f | wc -l 2>/dev/null)"

icon="📧"
syncicon=""

[ "$unread" = "0" ] && [ "$icon" = "" ] || echo "📬 $unread $syncicon"
