#!/bin/bash

# i3blocks newsboat module.
# Displays number of unread news items and an loading icon if updating.
# When clicked, brings up `newsboat`.

#cat /tmp/updatenews 2>/dev/null || echo "$(newsboat -x print-unread | awk '{ print "📰 " $1}' | sed s/^0$//g)$(cat ~/.config/newsboat/.update 2>/dev/null)"
cmd="$(newsboat -x print-unread | awk '{ print "📰 " $1}' | sed s/^0$//g)$(cat ~/.config/newsboat/.update 2>/dev/null)"

case $BLOCK_BUTTON in
	1) setsid "$TERMINAL" -e newsboat && echo $cmd;;
	2) setsid updatenews > /dev/null & exit ;;
esac
echo $cmd
