[colors]

# Default colors
[colors.primary]
background = "0x2E3440"  # Nord Polar Night 0
foreground = "0xD8DEE9"  # Nord Snow 4

# Cursor colors
[colors.cursor]
text = "0x2E3440"        # Background color
cursor = "0xD8DEE9"      # Foreground color

# Normal colors
[colors.normal]
black   = "0x3B4252"     # Nord Polar Night 1
red     = "0xBF616A"     # Nord Frost 1
green   = "0xA3BE8C"     # Nord Frost 3
yellow  = "0xEBCB8B"     # Nord Frost 5
blue    = "0x81A1C1"     # Nord Frost 8
magenta = "0xB48EAD"     # Nord Frost 4
cyan    = "0x8FBCBB"     # Nord Frost 6
white   = "0xE5E9F0"     # Nord Snow 3

# Bright colors
[colors.bright]
black   = "0x4C566A"     # Nord Polar Night 2
red     = "0xBF616A"     # Nord Frost 1
green   = "0xA3BE8C"     # Nord Frost 3
yellow  = "0xEBCB8B"     # Nord Frost 5
blue    = "0x81A1C1"     # Nord Frost 8
magenta = "0xB48EAD"     # Nord Frost 4
cyan    = "0x8FBCBB"     # Nord Frost 6
white   = "0xECEFF4"     # Nord Snow 0

[font]
size = 9

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

