# REF: https://www.jamesridgway.co.uk/dotfiles-with-github-travis-ci-and-docker/
FROM ubuntu:20.04
ENV DOCKER=yes

# update
RUN apt-get -qq update
RUN DEBIAN_FRONTEND="noninteractive" apt-get install git sudo zsh stow make neovim \
	libx11-dev build-essential curl wget libxrandr-dev libxi-dev libxinerama-dev libxft-dev -qq -y

# creating test user, with no sudo password
RUN useradd -m -s /bin/zsh testuser
RUN usermod -aG sudo testuser
RUN echo "testuser   ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers

# add dotfiles
ADD . /home/testuser/dotfiles/

# switch to test user
RUN chown -R testuser:testuser /home/testuser
USER testuser
ENV HOME /home/testuser
WORKDIR /home/testuser/dotfiles

# run the install
RUN install_scripts/install_xubuntu.sh

# simlink dotfiles
# overwrite $HOME/.profile
RUN rm -f $HOME/.profile
RUN stow --no-folding home

WORKDIR /home/testuser/

CMD ["/bin/zsh", "--login"]
