# bash profile

# custom ls 
alias ll="ls -ltrh"

# colours
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

# grep
alias grep='grep --color=auto'

# human readable memory by default
alias du="du -h"
alias df="df -h"

# being careful about what I move and delete
alias rm="rm -i"
alias mv="mv -i"

# remove ROOT splash screen
alias rt="root -l"

# terminal prompt (PS1), show git branch
parse_git_branch() {
	git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="[ \d \t \u: ] \[\033[32m\]\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "

# default editor
export EDITOR=vim

# kerberos authentication
alias kcern="kinit -f -r7d -A SDYSCH@CERN.CH"

# bash aliases
source ~/.bash_aliases
