#!/bin/bash

# Notify via notify-send if battery is <35%

[ "$(cat /sys/class/power_supply/BAT0/status)" = "Charging" ] && exit
[ "$(cat /sys/class/power_supply/BAT0/capacity)" -lt 35 ] &&
notify-send -i $ICONSDIR/batteryLow.png -u critical "WARNING" "Battery less than 35%!"
