#!/bin/bash
# take screenshot of desktop, blur, lock
#REF: https://michaelabrahamsen.com/posts/custom-lockscreen-i3lock/

tmpbg="/tmp/screen.png"

# take a screenshot
scrot "$tmpbg"

# blur the screenshot by resizing and scaling back up
convert "$tmpbg" -filter Gaussian -thumbnail 20% -sample 500% "$tmpbg"

# lock the screen with the blurred screenshot
i3lock -i "$tmpbg" -e -f -t

rm $tmpbg
