#!/bin/bash

TASK_COMMAND="task ${@}"

# check data directory exists
if [ ! -d "$TASKDIR" ]; then
	echo "Could not load task directory!"
	exit 1
fi

# Check if --task-git-push is passed as an argument.
PUSH=0
for i
do
	if [ "$i" == "--task-git-push" ]; then
		# Set the PUSH flag, and remove this from the arguments list.
		PUSH=1
		shift
	fi
done

# Call task, commit files and push if flag is set.
task $@
cd $TASKDIR
git add -A
git commit -m "$TASK_COMMAND" > /dev/null
if [ "$PUSH" == 1 ]; then
	git push origin master > /dev/null
fi
exit 0
