# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/afs/cern.ch/user/s/sdysch/.oh-my-zsh"

# theme
ZSH_THEME="powerlevel9k/powerlevel9k"

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user time dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs)

POWERLEVEL9K_SHORTEN_DIR_LENGTH=1


# plugins
plugins=(
	git
	tmux
	zsh-syntax-highlighting
	zsh-autosuggestions
	z
)

source $ZSH/oh-my-zsh.sh

# common aliases
source $HOME/.zsh_aliases_common

# lxplus 
source $HOME/.zsh_aliases
