name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  gitleaks:
    uses: ./.github/workflows/gitleaks.yml

  python:
    needs: gitleaks
    uses: ./.github/workflows/python_lint.yml

  lua:
    needs: gitleaks
    uses: ./.github/workflows/lua_lint.yml

  shell:
    needs: gitleaks
    uses: ./.github/workflows/shellcheck.yml

  install_arch:
    needs:
      - python
      - lua
      - shell
    uses: ./.github/workflows/install_arch.yml

  docker_build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: install_arch
    uses: ./.github/workflows/docker.yml
