name: Install
on: [push]
jobs:
    Installation:
        runs-on: ubuntu-latest
        steps:
            uses: actions/checkout@v2
            - run: |
                sudo apt-get update
                sudo apt-get --assume-yes install stow vim git
                source install_scripts/install_packages.sh
                stow --no-folding home
