name: Installation
on: [push]
jobs:
    dist:
        runs-on: ubuntu-latest
    steps:
        - name: Update
        - run: apt-get update
        - run: apt-get --assume-yes install stow vim git
        - name: Install
        - run: source install_scripts/install_packages.sh
        - run: stow --no-folding home
