name: Install Xubuntu
on:
  push:
    paths:
      - 'setups/common/**'
      - 'setups/arch/**'

jobs:
  Installation:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --init

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          set -euo pipefail
          pacman -Sy --noconfirm stow git base-devel zsh

      - name: Run install script
        run: |
          set -euo pipefail
          source install_scripts/install_arch.sh

      - name: Stow configs
        run: |
          set -euo pipefail
          cd setups
          stow --no-folding arch --target=$HOME --adopt

      - name: "Check zsh"
        run: zsh -i -c 'echo "zsh okay"'

      - name: "Check nvim"
        run: nvim --headless -c 'echo "nvim okay"' -c 'qa!'  

      - name: "Check suckless"
        run: |
          which dwm
          which dwmblocks
          which dmenu
